### ISSUE TITLE
orb-babel support

### ISSUE THREAD

**Issue by gsingh93** [anticomputer/emacs-codeql#3]
Hi, thanks for this great package!

I'm wondering if you have thoughts on supporting `org-babel`, so that I can write and run queries in `#begin_src`/`#end_src` blocks?

**Comment by gsingh93** [comment]
I figured out that to get syntax highlighting (but not fully query execution), I can use `#+begin_src ql-tree-sitter`. It would be nice to document this in the README.

**Comment by anticomputer** [comment]
> Hi, thanks for this great package!
> 
> I'm wondering if you have thoughts on supporting `org-babel`, so that I can write and run queries in `#begin_src`/`#end_src` blocks?

I have not explored org-babel support in terms of active query running support, but I'll take a look to see if there's a flow that makes sense. I think the main challenge is that a lot of the query running logic is managed buffer local to the query buffer itself as opposed to a global state.

**Comment by gsingh93** [comment]
Could you elaborate on the issues around buffer local vs. global state? What exactly would the difference be between the following org-babel block as opposed to just having that QL code in it's own file?
```
#+begin_src ql-tree-sitter
from Function f
select f
#+end_src
```

Also as a side note, I don't know if you have any experience adding support to org-babel for executing code blocks, but just in case you don't here's a simple package I made that you could use for reference: https://github.com/gsingh93/ob-bitfield/blob/main/ob-bitfield.el

**Comment by anticomputer** [comment]
> Could you elaborate on the issues around buffer local vs. global state? What exactly would the difference be between the following org-babel block as opposed to just having that QL code in it's own file?
> 
> ```
> #+begin_src ql-tree-sitter
> from Function f
> select f
> #+end_src
> ```
> 
> Also as a side note, I don't know if you have any experience adding support to org-babel for executing code blocks, but just in case you don't here's a simple package I made that you could use for reference: https://github.com/gsingh93/ob-bitfield/blob/main/ob-bitfield.el

emacs-codeql was designed to maintain a significant amount of buffer-local state associated to the ql file buffer (each ql buffer has a dedicated buffer-local query server process, needs an active database associated to it, etc). This state is designed to be manipulated interactively through the transient UX and there is no sense of a global or default query server and database. One way would be to pass through e.g. a database path via the source block parameters and have sensible defaults for an ephemeral query server run. That still leaves the query result rendering itself, which currently does quite a bit of trickery to render into dedicated org-mode buffers which would not render into org-babel result blocks that well I don't think.

It certainly could be done but it's not something I have on my personal roadmap currently.
